language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

before_install:
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install gfortran

install:
  - travis_wait pip install scipy
  - pip install Cython
  - pip install -r requirements.txt

script: python setup.py test
